<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="OneGeneratorOneConsumer_4_10x" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="cochicde" Date="2025-04-27">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI0" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="OneGeneratorOneConsumer" Type="OneGeneratorOneConsumer_4" x="100" y="-500">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_1" Type="OneGeneratorOneConsumer_4" x="0" y="0">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_2" Type="OneGeneratorOneConsumer_4" x="0" y="400">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_3" Type="OneGeneratorOneConsumer_4" x="-100" y="800">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_4" Type="OneGeneratorOneConsumer_4" x="-300" y="1200">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_5" Type="OneGeneratorOneConsumer_4" x="1900" y="300">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_6" Type="OneGeneratorOneConsumer_4" x="2000" y="-600">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_7" Type="OneGeneratorOneConsumer_4" x="1800" y="700">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_8" Type="OneGeneratorOneConsumer_4" x="1900" y="-100">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_9" Type="OneGeneratorOneConsumer_4" x="1500" y="1100">
		</SubApp>
		<EventConnections>
			<Connection Source="OneGeneratorOneConsumer_3.CNF" Destination="OneGeneratorOneConsumer_4.EI0" dx1="63.16" dx2="63.16" dy="200"/>
			<Connection Source="OneGeneratorOneConsumer_2.CNF" Destination="OneGeneratorOneConsumer_3.EI0" dx1="63.16" dx2="63.16" dy="200"/>
			<Connection Source="OneGeneratorOneConsumer_1.CNF" Destination="OneGeneratorOneConsumer_2.EI0" dx1="63.16" dx2="63.16" dy="194.74"/>
			<Connection Source="OneGeneratorOneConsumer.CNF" Destination="OneGeneratorOneConsumer_1.EI0" dx1="63.16" dx2="63.16" dy="252.63"/>
			<Connection Source="OneGeneratorOneConsumer_8.CNF" Destination="OneGeneratorOneConsumer_5.EI0" dx1="63.16" dx2="63.16" dy="194.74"/>
			<Connection Source="OneGeneratorOneConsumer_7.CNF" Destination="OneGeneratorOneConsumer_9.EI0" dx1="63.16" dx2="63.16" dy="200"/>
			<Connection Source="OneGeneratorOneConsumer_5.CNF" Destination="OneGeneratorOneConsumer_7.EI0" dx1="63.16" dx2="63.16" dy="200"/>
			<Connection Source="OneGeneratorOneConsumer_6.CNF" Destination="OneGeneratorOneConsumer_8.EI0" dx1="63.16" dx2="63.16" dy="252.63"/>
			<Connection Source="OneGeneratorOneConsumer_4.CNF" Destination="OneGeneratorOneConsumer_6.EI0" dx1="968.42"/>
			<Connection Source="OneGeneratorOneConsumer_9.CNF" Destination="CNF" dx1="2226.32"/>
			<Connection Source="EI0" Destination="OneGeneratorOneConsumer.EI0" dx1="2489.47"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
