<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="OneGeneratorOneConsumer_1000x" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="cochicde" Date="2025-04-27">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI0" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="OneGeneratorOneConsumer" Type="OneGeneratorOneConsumer_100x" x="3100" y="0">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_6" Type="OneGeneratorOneConsumer_100x" x="5300" y="600">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_9" Type="OneGeneratorOneConsumer_100x" x="5200" y="1800">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_4" Type="OneGeneratorOneConsumer_100x" x="3000" y="2200">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_5" Type="OneGeneratorOneConsumer_100x" x="5300" y="100">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_1" Type="OneGeneratorOneConsumer_100x" x="3100" y="500">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_7" Type="OneGeneratorOneConsumer_100x" x="5200" y="1200">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_2" Type="OneGeneratorOneConsumer_100x" x="3000" y="1100">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_3" Type="OneGeneratorOneConsumer_100x" x="3000" y="1700">
		</SubApp>
		<SubApp Name="OneGeneratorOneConsumer_8" Type="OneGeneratorOneConsumer_100x" x="5200" y="2300">
		</SubApp>
		<EventConnections>
			<Connection Source="OneGeneratorOneConsumer_5.CNF" Destination="OneGeneratorOneConsumer_6.EI0" dx1="63.16" dx2="63.16" dy="247.37"/>
			<Connection Source="OneGeneratorOneConsumer_9.CNF" Destination="OneGeneratorOneConsumer_8.EI0" dx1="63.16" dx2="63.16" dy="247.37"/>
			<Connection Source="OneGeneratorOneConsumer.CNF" Destination="OneGeneratorOneConsumer_1.EI0" dx1="63.16" dx2="63.16" dy="252.63"/>
			<Connection Source="OneGeneratorOneConsumer_4.CNF" Destination="OneGeneratorOneConsumer_5.EI0" dx1="468.42"/>
			<Connection Source="OneGeneratorOneConsumer_2.CNF" Destination="OneGeneratorOneConsumer_3.EI0" dx1="63.16" dx2="63.16" dy="300"/>
			<Connection Source="OneGeneratorOneConsumer_6.CNF" Destination="OneGeneratorOneConsumer_7.EI0" dx1="63.16" dx2="63.16" dy="300"/>
			<Connection Source="OneGeneratorOneConsumer_3.CNF" Destination="OneGeneratorOneConsumer_4.EI0" dx1="63.16" dx2="63.16" dy="247.37"/>
			<Connection Source="OneGeneratorOneConsumer_1.CNF" Destination="OneGeneratorOneConsumer_2.EI0" dx1="63.16" dx2="63.16" dy="300"/>
			<Connection Source="OneGeneratorOneConsumer_7.CNF" Destination="OneGeneratorOneConsumer_9.EI0" dx1="63.16" dx2="63.16" dy="300"/>
			<Connection Source="EI0" Destination="OneGeneratorOneConsumer.EI0" dx1="1731.58"/>
			<Connection Source="OneGeneratorOneConsumer_8.CNF" Destination="CNF" dx1="3184.21"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
