<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="SIFB025" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="cochicde" Date="2025-05-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI0" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DINT_TO_UINT_1" Type="F_DINT_TO_UINT" x="1200" y="600">
		</FB>
		<FB Name="F_UINT_TO_INT_2" Type="F_UINT_TO_INT" x="2300" y="600">
		</FB>
		<FB Name="F_UINT_TO_INT" Type="F_UINT_TO_INT" x="2300" y="0">
		</FB>
		<FB Name="F_DINT_TO_UINT" Type="F_DINT_TO_UINT" x="1200" y="0">
		</FB>
		<FB Name="F_UINT_TO_INT_3" Type="F_UINT_TO_INT" x="5100" y="600">
		</FB>
		<FB Name="F_INT_TO_UINT_2" Type="F_INT_TO_UINT" x="3900" y="600">
		</FB>
		<FB Name="GeneratorInt_1" Type="performance::GeneratorInt" x="0" y="600">
		</FB>
		<FB Name="F_INT_TO_UINT_1" Type="F_INT_TO_UINT" x="3900" y="0">
		</FB>
		<FB Name="GeneratorInt" Type="performance::GeneratorInt" x="0" y="0">
		</FB>
		<FB Name="F_UINT_TO_INT_1" Type="F_UINT_TO_INT" x="5100" y="0">
		</FB>
		<EventConnections>
			<Connection Source="GeneratorInt_1.INITO" Destination="F_DINT_TO_UINT_1.REQ"/>
			<Connection Source="F_DINT_TO_UINT_1.CNF" Destination="F_UINT_TO_INT_2.REQ"/>
			<Connection Source="F_UINT_TO_INT_2.CNF" Destination="F_INT_TO_UINT_2.REQ"/>
			<Connection Source="F_DINT_TO_UINT.CNF" Destination="F_UINT_TO_INT.REQ"/>
			<Connection Source="F_UINT_TO_INT.CNF" Destination="F_INT_TO_UINT_1.REQ"/>
			<Connection Source="GeneratorInt.INITO" Destination="F_DINT_TO_UINT.REQ"/>
			<Connection Source="F_INT_TO_UINT_2.CNF" Destination="F_UINT_TO_INT_3.REQ"/>
			<Connection Source="F_UINT_TO_INT_1.CNF" Destination="GeneratorInt_1.REQ" dx1="63.16" dx2="63.16" dy="294.74"/>
			<Connection Source="F_INT_TO_UINT_1.CNF" Destination="F_UINT_TO_INT_1.REQ"/>
			<Connection Source="EI0" Destination="GeneratorInt.REQ" dx1="2284.21"/>
			<Connection Source="F_UINT_TO_INT_3.CNF" Destination="CNF" dx1="1447.37"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="GeneratorInt_1.RD" Destination="F_DINT_TO_UINT_1.IN"/>
			<Connection Source="F_DINT_TO_UINT_1.OUT" Destination="F_UINT_TO_INT_2.IN"/>
			<Connection Source="F_UINT_TO_INT_2.OUT" Destination="F_INT_TO_UINT_2.IN"/>
			<Connection Source="F_DINT_TO_UINT.OUT" Destination="F_UINT_TO_INT.IN"/>
			<Connection Source="F_UINT_TO_INT.OUT" Destination="F_INT_TO_UINT_1.IN"/>
			<Connection Source="GeneratorInt.RD" Destination="F_DINT_TO_UINT.IN"/>
			<Connection Source="F_INT_TO_UINT_2.OUT" Destination="F_UINT_TO_INT_3.IN"/>
			<Connection Source="F_INT_TO_UINT_1.OUT" Destination="F_UINT_TO_INT_1.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
