<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="SIFB050" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="cochicde" Date="2025-05-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI0" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DINT_TO_UINT_1" Type="F_DINT_TO_UINT" x="1300" y="600">
		</FB>
		<FB Name="F_DINT_TO_UINT_4" Type="F_DINT_TO_UINT" x="1300" y="2500">
		</FB>
		<FB Name="GeneratorInt" Type="performance::GeneratorInt" x="0" y="0">
		</FB>
		<FB Name="GeneratorInt_2" Type="performance::GeneratorInt" x="0" y="1200">
		</FB>
		<FB Name="GeneratorInt_1" Type="performance::GeneratorInt" x="0" y="600">
		</FB>
		<FB Name="F_DINT_TO_UINT_3" Type="F_DINT_TO_UINT" x="1300" y="1800">
		</FB>
		<FB Name="F_DINT_TO_UINT_2" Type="F_DINT_TO_UINT" x="1300" y="1200">
		</FB>
		<FB Name="GeneratorInt_4" Type="performance::GeneratorInt" x="0" y="2500">
		</FB>
		<FB Name="F_DINT_TO_UINT" Type="F_DINT_TO_UINT" x="1300" y="0">
		</FB>
		<FB Name="GeneratorInt_3" Type="performance::GeneratorInt" x="0" y="1800">
		</FB>
		<EventConnections>
			<Connection Source="GeneratorInt_1.INITO" Destination="F_DINT_TO_UINT_1.REQ"/>
			<Connection Source="F_DINT_TO_UINT_1.CNF" Destination="GeneratorInt_2.REQ" dx1="63.16" dx2="63.16" dy="300"/>
			<Connection Source="GeneratorInt_4.INITO" Destination="F_DINT_TO_UINT_4.REQ"/>
			<Connection Source="GeneratorInt.INITO" Destination="F_DINT_TO_UINT.REQ"/>
			<Connection Source="GeneratorInt_2.INITO" Destination="F_DINT_TO_UINT_2.REQ"/>
			<Connection Source="F_DINT_TO_UINT.CNF" Destination="GeneratorInt_1.REQ" dx1="63.16" dx2="63.16" dy="294.74"/>
			<Connection Source="GeneratorInt_3.INITO" Destination="F_DINT_TO_UINT_3.REQ"/>
			<Connection Source="F_DINT_TO_UINT_3.CNF" Destination="GeneratorInt_4.REQ" dx1="63.16" dx2="63.16" dy="347.37"/>
			<Connection Source="F_DINT_TO_UINT_2.CNF" Destination="GeneratorInt_3.REQ" dx1="63.16" dx2="63.16" dy="294.74"/>
			<Connection Source="EI0" Destination="GeneratorInt.REQ" dx1="2284.21"/>
			<Connection Source="F_DINT_TO_UINT_4.CNF" Destination="CNF" dx1="2273.68"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="GeneratorInt_1.RD" Destination="F_DINT_TO_UINT_1.IN"/>
			<Connection Source="GeneratorInt_4.RD" Destination="F_DINT_TO_UINT_4.IN"/>
			<Connection Source="GeneratorInt.RD" Destination="F_DINT_TO_UINT.IN"/>
			<Connection Source="GeneratorInt_2.RD" Destination="F_DINT_TO_UINT_2.IN"/>
			<Connection Source="GeneratorInt_3.RD" Destination="F_DINT_TO_UINT_3.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
